-- Bootsing initial schema: per-user events, meta (categories/weeks/settings), and preferences.
-- Single-user today (app scopes every query to DEFAULT_USER_ID via the service-role key),
-- but every table carries user_id + RLS so real auth can be added later without a reshape.

create table public.events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  name text not null,
  venue text not null default '',
  cat text not null,
  starts date not null,
  ends date not null,
  cost text not null default '',
  description text not null default '',
  link text not null default '',
  approx boolean not null default false,
  genre text
);
create index events_user_starts_idx on public.events (user_id, starts);

create table public.categories (
  user_id uuid not null,
  key text not null,
  label text not null,
  color text not null,
  groups text[] not null default '{}',
  position int not null default 0,
  primary key (user_id, key)
);

create table public.weeks (
  user_id uuid not null,
  position int not null,
  week_start date not null,
  week_end date not null,
  primary key (user_id, position)
);

create table public.app_settings (
  user_id uuid primary key,
  genre_labels jsonb not null default '{}',
  group_labels jsonb not null default '{}',
  group_colors jsonb not null default '{}'
);

create table public.preferences (
  user_id uuid primary key,
  intro text not null default '',
  sections jsonb not null default '[]'
);

alter table public.events enable row level security;
alter table public.categories enable row level security;
alter table public.weeks enable row level security;
alter table public.app_settings enable row level security;
alter table public.preferences enable row level security;

-- Per-user policies for future auth. No authenticated users exist yet, and the app uses the
-- service-role key (which bypasses RLS), so these grant nothing today but are ready for later.
create policy "own events" on public.events for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own categories" on public.categories for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own weeks" on public.weeks for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own app_settings" on public.app_settings for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own preferences" on public.preferences for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
